<?php

namespace App\Views;

use App\App;
use Core\View;

class Navigation extends View
{
    public function render($template_path = ROOT . '/app/templates/navigation.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        if (App::$session->getUser()) {
            if (App::$session->getUser()['email'] == 'santa@santa.lt') {
                return [
                    'Wishes' => [
                        'link' => '../santa/wishes.php'
                    ],
                    'Messages' => [
                        'link' => '../santa/messages.php'
                    ],
                    'Logout' => [
                        'link' => '../logout.php'
                    ]
                ];
            } else {
                return [
                    'Wishes' => [
                        'link' => '../index.php'
                    ],
                    'Make a wish' => [
                        'link' => '../admin/newWish.php'
                    ],
                    'My' => [
                        'link' => '../admin/myWishes.php'
                    ],
                    'Logout' => [
                        'link' => '../logout.php'
                    ]
                ];
            }
        } else {
            return [
                'Wishes' => [
                    'link' => '../index.php'
                ],
                'Register' => [
                    'link' => '../register.php'
                ],
                'Login' => [
                    'link' => '../login.php'
                ],
                'About' => [
                    'link' => '../about.php'
                ]
            ];
        }
    }
}